name: sentinel
description: A Dart and Flutter project automatic test runner to run tests automatically as files change. Inspired by Jest and Ruby's Guard.
version: 2.2.3
homepage: https://github.com/asartalo/sentinel

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.4.2
  equatable: ^2.0.5
  file: ^7.0.0
  glob: ^2.1.0
  path: ^1.8.2
  watcher: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  conventional: ^0.4.0
  coverage: ^1.7.1
  git_hooks: ^1.0.1
  lint: ^2.2.0
  test: ^1.24.9

executables:
  sentinel:
