name: sentinel
description: A Dart and Flutter project automatic test runner to run tests automatically as files change. Inspired by Jest and Ruby's Guard.
version: 2.1.1
homepage: https://github.com/asartalo/sentinel

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ansicolor: ^2.0.1
  args: ^2.0.0
  equatable: ^2.0.0
  file: ^6.1.0
  watcher: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  conventional: ^0.2.4
  coverage: ^1.0.1
  git_hooks:
    git:
      url: https://github.com/asartalo/git_hooks.git
      ref: null-safety-2
  lint: ^1.5.1
  test: ^1.16.5

executables:
  sentinel: