name: build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2

  test:
    name: Tests
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    needs: commitlint
    outputs:
      branch: ${{ steps.branchinfo.outputs.branch }}

    steps:
      - name: Store the branch name
        id: branchinfo
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Check if we were able to save branch info
        run: echo ${{ steps.branchinfo.outputs.branch }}

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      # Checkout
      - uses: actions/checkout@v4

      - name: Get dependencies
        run: dart pub get

      - name: Check dart formatting
        run: dart format --set-exit-if-changed .

      - name: Statically analyze the Dart code for any errors.
        run: dart analyze .

      - name: Run Tests with coverage
        run: dart run coverage:test_with_coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: coverage/lcov.info

  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.outputs.branch == 'main' }}

    steps:
      - run: echo ${{ needs.test.outputs.branch }}

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: dart pub get

      - name: Install release_tools
        run: dart pub global activate release_tools

      - name: Hookup pub tools
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Check if pub tools are available
        run: which release_tools

      - name: Prepare release
        run: |
          release_tools prepare_release -w
          cat VERSION.txt || echo "No Release"

      - name: Get Release Info
        id: releaseInfo
        run: |
          if [ -e VERSION.txt ]
          then
            shouldRelease="yes"
            releaseVersion=$(cat VERSION.txt)
            summary=$(cat RELEASE_SUMMARY.txt)
            echo "version=${releaseVersion}" >> $GITHUB_OUTPUT
            {
              echo 'summary<<EOF'
              echo summary
              echo EOF
            } >> $GITHUB_OUTPUT
          else
            shouldRelease="false"
          fi
          echo "shouldRelease=${shouldRelease}" >> $GITHUB_OUTPUT

      - name: Update version for sentinel
        run: release_tools update_version --file="lib/sentinel_version.dart" ${{  steps.releaseInfo.outputs.version  }}

      - name: Commit Release
        if: steps.releaseInfo.outputs.shouldRelease == 'yes'
        run: |
          git diff
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "chore(release): prepare release for ${{ steps.releaseInfo.outputs.version }}"
          git push

      - name: Create Release
        if: steps.releaseInfo.outputs.shouldRelease == 'yes'
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.PAT }}
          tag: ${{ steps.releaseInfo.outputs.version }}
          name: Release ${{ steps.releaseInfo.outputs.version }}
          body: |
            Changes in this Release

            ${{ steps.releaseInfo.outputs.summary }}

          draft: false
          prerelease: false
